[build]
  command = "npm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# Enable functions for this site
[context.production]
  functions = "netlify/functions"

[context.deploy-preview]
  functions = "netlify/functions"

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200