[build]
  command = "npm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/basic"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/basic"
  status = 200
  force = true