[build]
  command = "npm run build:client"
  publish = "dist/spa"
  # The functions directory is now defined below

# All function settings are combined into ONE section
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "firebase-admin"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true