# CORRECT AND FINAL netlify.toml

[build]
  command = "pnpm build"
  publish = "client/dist"

# All function settings are now combined into ONE section
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true